name: functions

on:
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-20.04
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            functions/healthcheck/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('functions/healthcheck/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('functions/healthcheck/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Add Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add Zig
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://ziglang.org/download/0.10.0/zig-linux-x86_64-0.10.0.tar.xz'
          name: 'zig'
          version: '0.10.0'
          command: tar -xvf zig # 'zig-linux-x86_64-0.10.0/zig'

      - name: Fix Zig
        working-directory: /opt/hostedtoolcache/zig/0.10.0/x64
        run: |
          mv zig-linux-x86_64-0.10.0/zig zig
          rm -rf zig-linux-x86_64-0.10.0

      - name: Add Cargo Lambda
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/cargo-lambda/cargo-lambda/releases/download/v0.12.0/cargo-lambda-v0.12.0.x86_64-unknown-linux-musl.tar.gz'
          name: 'cargo-lambda'
          version: '0.12.0'

      - name: Mic Check
        run: |
          cargo lambda --version
          zig version

      - name: Build - Healthcheck
        working-directory: functions/healthcheck
        run: make
