name: functions

on:
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-20.04
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/sccache
          # target (don't want target/lambda?)
          # key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          key: ${{ runner.os }}-cargo-test
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Add Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add Zig
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://ziglang.org/download/0.10.0/zig-linux-x86_64-0.10.0.tar.xz'
          name: 'zig'
          version: '0.10.0'

      - name: Install ScCache
        run: cargo install sccache

      - name: Install Cargo Lambda
        env:
          RUSTC_WRAPPER: sccache
        run: cargo install cargo-lambda

      # - name: Build
      #   working-directory: functions
      #   env:
      #     RUSTC_WRAPPER: sccache
      #   run: ./build.sh

      # - name: Upload Artifacts
      #   working-directory: functions
      #   run: upload.sh -b ${{ secrets.BUCKET }} -p ${{ secrets.PREFIX }}
        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: Dev
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Assume Role
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         role-to-assume: ${{ secrets.ROLE }}
  #         role-session-name: GitHub-Action-Role
  #         aws-region: ${{ env.AWS_REGION }}

  #     - run: |
  #         echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
  #         commit_hash=`git rev-parse HEAD`
  #         aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures