name: gofmt

on:
  push:
    paths:
      - '.github/workflows/gofmt.yml'
      - 'terraform/**'

jobs:
  fmt:
    name: Check gofmt
    runs-on: ubuntu-20.04
    steps:
      - name: Add Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'terraform/go.mod'

      - name: Run
        working-directory: 'terraform'
        run: gofmt -l -d .