name: gofmt

on:
  push:
    paths:
      - '.github/workflows/gofmt.yml'
      - 'terraform/**'

jobs:
  uses: Jerome1337/gofmt-action@v1.0.5
  with:
    gofmt-path: './terraform'
    gofmt-flags: '-l -d'