name: terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run plan against'
        type: environment
        required: true
      deploy:
        description: Apply terraform
        type: boolean
        required: false
        default: false
  push:
    paths:
      - '.github/workflows/terraform.yml'
      - 'terraform/**'
      - 'vtl/**'
      - 'schema/**'

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Add Node for CDKTF
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      # note: might be able to cache this, but it only takes like 10 seconds
      - name: Add CDKTF
        run: npm install --global cdktf-cli@0.14.3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: terraform/go.mod

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Plan
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          workingDirectory: terraform
          terraformVersion: 1.3.6
          cdktfVersion: 0.14.3
          stackName: ${{ github.event.inputs.environment || 'dev' }}
          mode: plan-only
          commentOnPr: false

      - name: Archive Plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          retention-days: 1
          path: |
            "terraform/cdktf.out/stacks/${{ github.event.inputs.environment || 'dev' }}/plan"

      - name: Deploy
        if: github.event_name == 'workflow_call' || format('{0}', github.event.inputs.deploy) == 'true'
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          workingDirectory: terraform
          terraformVersion: 1.3.6
          cdktfVersion: 0.14.3
          stackName: ${{ github.event.inputs.environment || 'dev' }}
          mode: auto-approve-apply
          commentOnPr: false
